### ISSUE TITLE
Compile error when including gwt-material-table into an existing GwtMaterialDesign 1.6 version project

### ISSUE THREAD

**Issue by zak905** [GwtMaterialDesign/gwt-material-table#24]
I have included gwt-material-table into dependency into the pom.xml and updated the module descriptor, but when I compile I get this error (which go away when I remove gwt-material-table): 

```
O] com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:121)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:296)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
[INFO] 	at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:67)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
[INFO] 	at com.google.gwt.dev.jjs.ast.JBinaryOperation.traverse(JBinaryOperation.java:83)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
[INFO] 	at com.google.gwt.dev.jjs.ast.JExpressionStatement.traverse(JExpressionStatement.java:42)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:95)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:351)
[INFO] 	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:149)
[INFO] 	at com.google.gwt.dev.jjs.ast.JIfStatement.traverse(JIfStatement.java:53)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:95)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:351)
[INFO] 	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:149)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:145)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:600)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:569)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:1505)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:870)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1305)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1038)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.precompile(JavaToJavaScriptCompiler.java:954)
[INFO] 	at com.google.gwt.dev.jjs.MonolithicJavaToJavaScriptCompiler.precompile(MonolithicJavaToJavaScriptCompiler.java:303)
[INFO] 	at com.google.gwt.dev.jjs.JavaScriptCompiler.precompile(JavaScriptCompiler.java:38)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:286)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:145)
[INFO] 	at com.google.gwt.dev.Compiler.run(Compiler.java:206)
[INFO] 	at com.google.gwt.dev.codeserver.Recompiler.doCompile(Recompiler.java:333)
[INFO] 	at com.google.gwt.dev.codeserver.Recompiler.compile(Recompiler.java:161)
[INFO] 	at com.google.gwt.dev.codeserver.Recompiler.recompile(Recompiler.java:119)
[INFO] 	at com.google.gwt.dev.codeserver.Outbox.recompile(Outbox.java:128)
[INFO] 	at com.google.gwt.dev.codeserver.JobRunner.recompile(JobRunner.java:81)
[INFO] 	at com.google.gwt.dev.codeserver.JobRunner.access$100(JobRunner.java:34)
[INFO] 	at com.google.gwt.dev.codeserver.JobRunner$2.run(JobRunner.java:73)
[INFO] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[INFO] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO] Caused by: java.lang.NoSuchMethodError: com.google.gwt.util.tools.Utility.close(Ljava/lang/AutoCloseable;)V
[INFO] 	at com.google.gwt.resources.rg.ImageResourceGenerator.getContentLength(ImageResourceGenerator.java:623)
[INFO] 	at com.google.gwt.resources.rg.ImageResourceGenerator.prepare(ImageResourceGenerator.java:584)
[INFO] 	at com.google.gwt.resources.rebind.context.AbstractClientBundleGenerator.initAndPrepare(AbstractClientBundleGenerator.java:1013)
[INFO] 	at com.google.gwt.resources.rebind.context.AbstractClientBundleGenerator.initAndPrepare(AbstractClientBundleGenerator.java:1039)
[INFO] 	at com.google.gwt.resources.rebind.context.AbstractClientBundleGenerator.generateIncrementally(AbstractClientBundleGenerator.java:419)
[INFO] 	at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:754)
[INFO] 	at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:160)
[INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:79)
[INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:276)
[INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:265)
[INFO] 	at com.google.gwt.dev.DistillerRebindPermutationOracle.getAllPossibleRebindAnswers(DistillerRebindPermutationOracle.java:87)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createStaticRebindExpression(UnifyAst.java:485)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createRebindExpression(UnifyAst.java:443)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.handleMagicMethodCall(UnifyAst.java:576)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.endVisit(UnifyAst.java:306)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:248)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO] 	... 59 more
[INFO]             [ERROR] at SimplePager.java(220): GWT.create(SimplePager$Resources.class)
[INFO]                com.google.gwt.dev.jjs.ast.JMethodCall
[INFO]             [ERROR] at SimplePager.java(220): (SimplePager$Resources) GWT.create(SimplePager$Resources.class)
[INFO]                com.google.gwt.dev.jjs.ast.JCastOperation
[INFO]             [ERROR] at SimplePager.java(220): SimplePager.DEFAULT_RESOURCES = (SimplePager$Resources) GWT.create(SimplePager$Resources.class)
[INFO]                com.google.gwt.dev.jjs.ast.JBinaryOperation
[INFO]             [ERROR] at SimplePager.java(220): SimplePager.DEFAULT_RESOURCES = (SimplePager$Resources) GWT.create(SimplePager$Resources.class)
[INFO]                com.google.gwt.dev.jjs.ast.JExpressionStatement
[INFO]             [ERROR] at SimplePager.java(219): {
[INFO]   SimplePager.DEFAULT_RESOURCES = (SimplePager$Resources) GWT.create(SimplePager$Resources.class);
[INFO] }
[INFO]                com.google.gwt.dev.jjs.ast.JBlock
[INFO]             [ERROR] at SimplePager.java(219): if (SimplePager.DEFAULT_RESOURCES == null) {
[INFO]   SimplePager.DEFAULT_RESOURCES = (SimplePager$Resources) GWT.create(SimplePager$Resources.class);
[INFO] }
[INFO]                com.google.gwt.dev.jjs.ast.JIfStatement
[INFO]             [ERROR] at SimplePager.java(218): {
[INFO]   if (SimplePager.DEFAULT_RESOURCES == null) {
[INFO]     SimplePager.DEFAULT_RESOURCES = (SimplePager$Resources) GWT.create(SimplePager$Resources.class);
[INFO]   }
[INFO]   return SimplePager.DEFAULT_RESOURCES;
[INFO] }
[INFO]                com.google.gwt.dev.jjs.ast.JBlock
[INFO]             [ERROR] at SimplePager.java(218): {
[INFO]   if (SimplePager.DEFAULT_RESOURCES == null) {
[INFO]     SimplePager.DEFAULT_RESOURCES = (SimplePager$Resources) GWT.create(SimplePager$Resources.class);
[INFO]   }
[INFO]   return SimplePager.DEFAULT_RESOURCES;
[INFO] }
[INFO]                com.google.gwt.dev.jjs.ast.JMethodBody
[INFO]             [ERROR] at SimplePager.java(218): private static SimplePager$Resources getDefaultResources();
[INFO] 
[INFO]                com.google.gwt.dev.jjs.ast.JMethod
[INFO]       [ERROR] Compiler returned false
[INFO]       [WARN] recompile failed
[INFO]       [WARN] continuing to serve previous version
```

**Comment by BenDol** [comment]
The data table only supports GMD 2.0+ you will need to update your GMD first before importing.
