### ISSUE TITLE
AddColumn

### ISSUE THREAD

**Issue by LeshaRB** [GwtMaterialDesign/gwt-material-table#43]
When I add columns in this method as in example, all work fine.

> protected void onLoad() {
>         super.onLoad();
> ...
> }

But when I add columns after table have been created, I have error

> Exception caught: Exception caught: (TypeError) : Cannot read property 'insert_37_g$' of undefined
> H3f_g$ @ AdminConsole-0.js:84934
> AdminConsole-0.js:84930 Exception: com.google.gwt.event.shared.UmbrellaException: Exception caught: Exception caught: (TypeError) : Cannot read property 'insert_37_g$' of undefined
> AdminConsole-0.js:84934 Error: com.google.gwt.event.shared.UmbrellaException: Exception caught: Exception caught: (TypeError) : Cannot read property 'insert_37_g$' of undefined
>     at oLc_g$.g1_g$ [as createError_0_g$] (AdminConsole-0.js:18358:10)
>     at oLc_g$.q1_g$ [as initializeBackingError_0_g$] (AdminConsole-0.js:18413:43)
>     at oLc_g$.a1_g$ (AdminConsole-0.js:18274:8)
>     at oLc_g$.G1_g$ (AdminConsole-0.js:18512:9)
>     at oLc_g$.O1_g$ (AdminConsole-0.js:18559:9)
>     at oLc_g$.hLc_g$ (AdminConsole-0.js:29041:9)
>     at oLc_g$ (AdminConsole-0.js:29105:10)
>     at nKc_g$.qKc_g$ [as fireEvent_0_g$] (AdminConsole-0.js:28653:20)
>     at _vd_g$.bwd_g$ [as fireEvent_0_g$] (AdminConsole-0.js:39089:22)
>     at OJc_g$ (AdminConsole-0.js:28549:17)
>     at _vd_g$.cwd_g$ [as fireValueChangedEvent_0_g$] (AdminConsole-0.js:39093:3)
>     at Uvd_g$ (AdminConsole-0.js:39032:29)
>     at X9_g$ (AdminConsole-0.js:19616:28)
>     at $9_g$ (AdminConsole-0.js:19672:16)
>     at AdminConsole-0.js:19652:14
> H3f_g$ @ AdminConsole-0.js:84934
> AdminConsole-0.js:84930 Caused by: com.google.web.bindery.event.shared.UmbrellaException: Exception caught: (TypeError) : Cannot read property 'insert_37_g$' of undefined
>

**Comment by LeshaRB** [comment]
**Presenter**

>     @Override
>     protected void onBind() {
>         super.onBind();
>         getView().addColumn(new TextColumn<ClientModel>() {
>             @Override
>             public String getValue(ClientModel clientModel) {
>                 return clientModel.getLastName();
>             }
>         });
>         // addColumns();
>     }

	
**View**	

> 	@Override
>     public void addColumn(TextColumn<ClientModel> textColumn) {
>         consoleTable.addColumn(textColumn, "TEST");
>     }

	
**ConsoleTable**

>     @UiField
>     MaterialDataTable consoleTable;
> 	...
>     public void addColumn(Column column, String header) {
>         logger.info(StringUtils.format("Column - %s, Header - %s", column, header));
>         consoleTable.addColumn(column, header);
>     }	


**Error**

ConsoleLogger.java:32 Column - Column{cell=gwt.material.design.client.ui.table.cell.TextCell@104, fieldUpdater=undefined, isDefaultSortAscending=true, isNumeric=false, name='undefined', headerWidth='undefined', hideOn=undefined, textAlign=undefined, styleProps=undefined, sortComparator=undefined}, Header - TEST
ConsoleLogger.java:32 Exception caught: Exception caught: (TypeError) : Cannot read property 'insert_11_g$' of undefined
Hwh_g$ @ ConsoleLogger.java:32
e1g_g$ @ SimpleConsoleLogHandler.java:36
s0g_g$ @ Logger.java:312
r0g_g$ @ Logger.java:302
P0g_g$ @ Logger.java:236
Sld_g$ @ LogConfiguration.java:169
ulb_g$ @ Impl.java:186
hlb_g$ @ Impl.java:293
(anonymous) @ Impl.java:77
ConsoleLogger.java:55 Exception: com.google.gwt.event.shared.UmbrellaException: Exception caught: Exception caught: (TypeError) : Cannot read property 'insert_11_g$' of undefined
ConsoleLogger.java:32 Error: com.google.gwt.event.shared.UmbrellaException: Exception caught: Exception caught: (TypeError) : Cannot read property 'insert_11_g$' of undefined
    at PWc_g$.pcb_g$ [as createError_0_g$] (Throwable.java:121)
    at PWc_g$.zcb_g$ [as initializeBackingError_0_g$] (Throwable.java:113)
    at PWc_g$.jcb_g$ (Throwable.java:74)
    at PWc_g$.Pcb_g$ (Exception.java:33)
    at PWc_g$.Xcb_g$ (RuntimeException.java:33)
    at PWc_g$.IWc_g$ (UmbrellaException.java:65)
    at PWc_g$ (UmbrellaException.java:26)
    at DVc_g$.GVc_g$ [as fireEvent_1_g$] (HandlerManager.java:129)
    at uHd_g$.wHd_g$ [as fireEvent_1_g$] (History.java:68)
    at cVc_g$ (ValueChangeEvent.java:43)
    at uHd_g$.xHd_g$ [as fireValueChangedEvent_0_g$] (History.java:77)
    at nHd_g$ (History.java:397)
    at elb_g$ (Impl.java:239)
    at hlb_g$ (Impl.java:291)
    at Impl.java:77
Hwh_g$ @ ConsoleLogger.java:32
Jwh_g$ @ ConsoleLogger.java:41
Iwh_g$ @ ConsoleLogger.java:36
e1g_g$ @ SimpleConsoleLogHandler.java:38
s0g_g$ @ Logger.java:312
r0g_g$ @ Logger.java:302
P0g_g$ @ Logger.java:236
Sld_g$ @ LogConfiguration.java:169
ulb_g$ @ Impl.java:186
hlb_g$ @ Impl.java:293
(anonymous) @ Impl.java:77
ConsoleLogger.java:55 Caused by: com.google.web.bindery.event.shared.UmbrellaException: Exception caught: (TypeError) : Cannot read property 'insert_11_g$' of undefined
>     @Override
>     protected void onBind() {
>         super.onBind();
>         getView().addColumn(new TextColumn<ClientModel>() {
>             @Override
>             public String getValue(ClientModel clientModel) {
>                 return clientModel.getLastName();
>             }
>         });
>         // addColumns();
>     }

	
**View**	

> 	@Override
>     public void addColumn(TextColumn<ClientModel> textColumn) {
>         consoleTable.addColumn(textColumn, "TEST");
>     }

	
**ConsoleTable**

>     @UiField
>     MaterialDataTable consoleTable;
> 	...
>     public void addColumn(Column column, String header) {
>         logger.info(StringUtils.format("Column - %s, Header - %s", column, header));
>         consoleTable.addColumn(column, header);
>     }	


**Error**

> 
> ConsoleLogger.java:32 Column - Column{cell=gwt.material.design.client.ui.table.cell.TextCell@104, fieldUpdater=undefined, isDefaultSortAscending=true, isNumeric=false, name='undefined', headerWidth='undefined', hideOn=undefined, textAlign=undefined, styleProps=undefined, sortComparator=undefined}, Header - TEST
> ConsoleLogger.java:32 Exception caught: Exception caught: (TypeError) : Cannot read property 'insert_11_g$' of undefined
> Hwh_g$ @ ConsoleLogger.java:32
> e1g_g$ @ SimpleConsoleLogHandler.java:36
> s0g_g$ @ Logger.java:312
> r0g_g$ @ Logger.java:302
> P0g_g$ @ Logger.java:236
> Sld_g$ @ LogConfiguration.java:169
> ulb_g$ @ Impl.java:186
> hlb_g$ @ Impl.java:293
> (anonymous) @ Impl.java:77
> ConsoleLogger.java:55 Exception: com.google.gwt.event.shared.UmbrellaException: Exception caught: Exception caught: (TypeError) : Cannot read property 'insert_11_g$' of undefined
> ConsoleLogger.java:32 Error: com.google.gwt.event.shared.UmbrellaException: Exception caught: Exception caught: (TypeError) : Cannot read property 'insert_11_g$' of undefined
>     at PWc_g$.pcb_g$ [as createError_0_g$] (Throwable.java:121)
>     at PWc_g$.zcb_g$ [as initializeBackingError_0_g$] (Throwable.java:113)
>     at PWc_g$.jcb_g$ (Throwable.java:74)
>     at PWc_g$.Pcb_g$ (Exception.java:33)
>     at PWc_g$.Xcb_g$ (RuntimeException.java:33)
>     at PWc_g$.IWc_g$ (UmbrellaException.java:65)
>     at PWc_g$ (UmbrellaException.java:26)
>     at DVc_g$.GVc_g$ [as fireEvent_1_g$] (HandlerManager.java:129)
>     at uHd_g$.wHd_g$ [as fireEvent_1_g$] (History.java:68)
>     at cVc_g$ (ValueChangeEvent.java:43)
>     at uHd_g$.xHd_g$ [as fireValueChangedEvent_0_g$] (History.java:77)
>     at nHd_g$ (History.java:397)
>     at elb_g$ (Impl.java:239)
>     at hlb_g$ (Impl.java:291)
>     at Impl.java:77
> Hwh_g$ @ ConsoleLogger.java:32
> Jwh_g$ @ ConsoleLogger.java:41
> Iwh_g$ @ ConsoleLogger.java:36
> e1g_g$ @ SimpleConsoleLogHandler.java:38
> s0g_g$ @ Logger.java:312
> r0g_g$ @ Logger.java:302
> P0g_g$ @ Logger.java:236
> Sld_g$ @ LogConfiguration.java:169
> ulb_g$ @ Impl.java:186
> hlb_g$ @ Impl.java:293
> (anonymous) @ Impl.java:77
> ConsoleLogger.java:55 Caused by: com.google.web.bindery.event.shared.UmbrellaException: Exception caught: (TypeError) : Cannot read property 'insert_11_g$' of undefined


What I do wrong? =(
Demo work fine... (where columns added in onLoad() method)

**Comment by LeshaRB** [comment]
This happens if the widget is alredy created.

For example my code

public class ConsoleTableColumn {
    private TextColumn textColumn;
    private String header;
}

public class ConsoleTable<T> extends Composite {
    private static final Logger logger = Logger.getLogger(ConsoleTable.class.getName());

    private static int ROW_COUNT_20 = 20;
    private static int ROW_COUNT_50 = 50;
    private static int ROW_COUNT_100 = 100;

    private int pageStart = 0;
    private int pageSize = 0;

    interface ConsoleTableUiBinder extends UiBinder<Widget, ConsoleTable> {
    }

    @UiField
    MaterialDataTable consoleTable;

    private MaterialDataPager pager;
    private ListDataSource<T> dataSource = new ListDataSource<T>();

    private static ConsoleTableUiBinder uiBinder = GWT.create(ConsoleTableUiBinder.class);

    public ConsoleTable() {
        initWidget(uiBinder.createAndBindUi(this));
    }

    @Override
    protected void onLoad() {
        super.onLoad();

        pager = new MaterialDataPager<>(consoleTable, dataSource);
        pager.setLimitOptions(ROW_COUNT_20, ROW_COUNT_50, ROW_COUNT_100);
        pager.setLimit(ROW_COUNT_20);

        // consoleTable.add(pager);
        // consoleTable.setRowCount(ROW_COUNT_20);
        // consoleTable.setRenderer(new ConsoleTableRender<>());
        //

        List<ConsoleTableColumn> consoleTableColumnList = new LinkedList<>();
        ConsoleTableColumn blockedColumn = new ConsoleTableColumn();
        blockedColumn.setTextColumn(new TextColumn<ClientModel>() {
            @Override
            public String getValue(ClientModel clientModel) {
                return String.valueOf(clientModel.isForcedBlock());
            }
        });
        blockedColumn.setHeader(ResLocale.INSTANCE.clientBlock());
        consoleTableColumnList.add(blockedColumn);

        logger.info(StringUtils.format("consoleTableColumnList size - %s", consoleTableColumnList.size()));

        consoleTableColumnList.forEach(col -> {
            logger.info(StringUtils.format("consoleTableColumnList col header - %s", col.getHeader()));
            consoleTable.addColumn(col.getTextColumn(), col.getHeader());
        });
    }

    public void setDataSource(List<T> dataSource) {
        this.dataSource.add(0, dataSource);
    }

    public void addColumn(Column column, String header) {
        logger.info(StringUtils.format("Column - %s, Header - %s", column, header));
        consoleTable.addColumn(column, header);
    }

    public int getPageStart() {
        return 10;
        // return pageStart;
    }

    public int getPageSize() {
        return 20;
        // return pageSize;
    }
}

All Work fine I can add different columns.

But when I add columns AFTER ConsoleTable<T> has been create.

I have error, which  describe upper.

**Comment by LeshaRB** [comment]
You can close this issue
I solved this problem
