### ISSUE TITLE
Remove columns

### ISSUE THREAD

**Issue by LeshaRB** [GwtMaterialDesign/gwt-material-table#58]
I try remove columns
```

    public void removeColumns() {
        logger.info(consoleTable.getColumns().size() + "");
        while (consoleTable.getColumns().size() > 0) {
            logger.info(consoleTable.getColumns().size() + " - ");
            consoleTable.removeColumn(0);
        }
    }
```

But have error

```
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'parentNode' of undefined
     at Unknown.QEc_g$(Node.java:190)
     at Unknown.aFc_g$(Node.java:307)
     at Unknown.xeh_g$(MaterialDataTable.java:218)
     at Unknown.zLj_g$(ConsoleTable.java:171)
     at Unknown.dC_g$(ClientsView.java:129)
     at Unknown.zA_g$(ClientsPresenter.java:253)
     at Unknown.yA_g$(ClientsPresenter.java:89)
     at Unknown.ab_g$(PresenterWidget.java:574)
     at Unknown.qb_g$(PresenterWidget.java:378)
     at Unknown.pb_g$(PresenterWidget.java:347)
     at Unknown.vVf_g$(RevealContentHandler.java:60)
     at Unknown.BVf_g$(RevealContentHandler.java:58)
     at Unknown.Z7b_g$(SchedulerImpl.java:50)
     at Unknown.D7b_g$(SchedulerImpl.java:183)
     at Unknown.y7b_g$(SchedulerImpl.java:347)
     at Unknown.R7b_g$(SchedulerImpl.java:78)
     at Unknown.v7b_g$(SchedulerImpl.java:141)
     at Unknown.i6b_g$(Impl.java:239)
     at Unknown.l6b_g$(Impl.java:291)
     at Unknown.anonymous(Impl.java:77)
```

**Comment by BenDol** [comment]
Seems to have been caused by https://github.com/GwtMaterialDesign/gwt-material-table/commit/c16bb2f566a1956435f0545b0a91cd1ff72cccde
